var Webflow = Webflow || [];
Webflow.push(function () {
$( "#dropdown-value-1" ).click(function() {
var DropdownResult1 = "Customer support";
var DropdownResult2 = "all company sizes";
var subHero1 = "4.8%";
var subHeroD1 = "Unemployment rate (September 2021)";
var subHero2 = "10.4 million";
var subHeroD2 ="Job openings (August 2021)";
var subHero3 = "63%";
var subHeroD3 ="Customer support teams hiring in the next 6 months";
var subHero4 = "67%";
var subHeroD4 ="Customer support teams that use remote freelancers";
var subHero5 = "32%";
var subHeroD5 ="Customer support workers who are fully remote";
var htCard1="flex";
var htHead1 ="Customer support teams are staffing up";
var htStat1 ="63%";
var htSubHead1 ="of customer support teams plan to hire in the next 6 months.";
var htCard2="flex";
var htHead2 ="Midsize companies are staffing up the most";
var htStat2 ="78%";
var htSubHead2 ="of midsize¹ companies plan to hire in the next 6 months. Just 40% of very small companies² plan to hire over that time.";
var htCard3="none";
var htHead3 ="Midsize companies are staffing up the most";
var htStat3 ="78%";
var htSubHead3 ="of midsize¹ companies plan to hire in the next 6 months. Just 40% of very small companies² plan to hire over that time.";
var htCard4="flex";
var htHead4 ="Customer support teams are staffing up";
var htStat4 ="63%";
var htSubHead4 ="of customer support teams plan to hire in the next 6 months.";
var htStat5 ="32%";
var htSubHead5 ="of managers said it’s hard to find talent for customer support roles.";
var htCard6="none";
var htHead6 ="Customer support teams are staffing up";
var htStat6 ="63%";
var htSubHead6 ="of customer support teams plan to hire in the next 6 months.";
var ExpWrap="flex";
var ExpTitle ="Experience level managers are looking to hire in customer support";
var Exp1="56%";
var Exp2="53%";
var Exp3="22%";
var Exp4="11%";
var Graph1="none";
var yellow1="0%";
var green1="0%";
var yellow2="0%";
var green2="0%";
var yellow3="0%";
var green3="0%";
var yellow4="0%";
var green4="0%";
var yellow5="0%";
var green5="0%";
var yellow6="0%";
var green6="0%";
var yellow7="0%";
var green7="0%";
var yellow8="0%";
var green8="0%";
var yellow9="0%";
var green9="0%";
var yellow10="0%";
var green10="0%";
var yellow11="0%";
var green11="0%";
var yellow12="0%";
var green12="0%";
var yellow13="0%";
var green13="0%";
var yellow14="0%";
var green14="0%";
var yellow15="0%";
var green15="0%";
var rwSection="flex";
var RwSubhead="Customer support teams plan to scale back remote-work options post-pandemic";
var round1="32%";
var round2="50%";
var round3="100%";
var round4="26%";
var round5="41%";
var round6="100%";
var round7="25%";
var round8="39%";
var round9="100%";
var relyingMain="Customer support teams are relying more on remote freelancers today than 1 year ago";
var relyingStat1="67%";
var relyingStat2="39%";
var relyingMain2="Customer support teams are relying more on remote freelancers today than 1 year ago";
var relyingStat3="28%";
var relyingStat4="28%";
var graph2="flex";
var graph2Title="Percentage of customer support teams that plan to use more remote freelancers in the future";
var firstTop="34%";
var firstBot="32%";
var secondTop="22%";
var secondBot="24%";
var singleWrap="none";
var singleTitle="x";
var singleStat="x";
var singleDesc="x";
var doubleWrap="grid";
var doubleTitle="Percentage of work done by remote freelancers";
var doubleStat1="12%";
var doubleDesc1="of customer support work is done by remote freelancers.";
var doubleStat2="15%";
var doubleDesc2="of administrative support work is done by remote freelancers.";
var graph3="none";
var difStat1="0%";
var difStat2="0%";
var difStat3="0%";
var difStat4="0%";
var difStat5="0%";
var difStat6="0%";
var difStat7="0%";
var difStat8="0%";
var difStat9="0%";
var difStat10="0%";
var difStat11="0%";
var difStat12="0%";
var difStat13="0%";
var difStat14="0%";
var difStat15="0%";
var turnover1 = "46%";
var turnoverDesc="of customer support managers said turnover within their team has increased compared to before the COVID-19 pandemic.";
var graph4="flex";
var graph4Title="title";
var graph4Desc="desc";
var lila1="100%";
var lila2="98%";
var lila3="88%";
var lila4="65%";
var lila5="60%";
var productivity="57% of customer support managers have changed how they measure worker productivity as a result of the COVID-19 pandemic.";
var round10="52%";
var round11="84%";
var round12="100%";
var round13="48%";
var round14="85%";
var round15="100%";
var round16="45.5%";
var round17="83%";
var round18="100%";
var round19="48%";
var round20="81%";
var round21="100%";
var round22="50%";
var round23="92%";
var round24="100%";
var conTitle1="Customer support managers are confident in their ability to hire";
var conStat1="74%";
var conDesc1="are confident in their ability to find and hire the talent they need.";
var conDesc12="Across all teams, managers who engaged more remote freelancers in the past 12 months are much more confident in their ability to hire than those who engaged fewer remote freelancers (81% vs. 58%).";
var conTitle2="Customer support managers are confident they can retain key workers";
var conStat2="81%";
var conDesc2="are confident in their ability to retain critical team members.";
var conTitle3="Customer support managers have the resources they need";
var conStat3="80%";
var conDesc3="are confident they have the resources needed to meet objectives.";
var conTitle4="Customer support managers have the skills they need on their team";
var conStat4="85%";
var conDesc4="of managers have the skills among their team members that they need to meet their objectives.";
var conTitle5="But full confidence is elusive.</br></br>Managers in IT and networking and web, mobile, and software development are the most confident across all 4 categories.</br></br>Managers in marketing are the least confident across all 4 categories.";
var conStat5="Only 16%";
var conDesc5="of managers across teams are “fully confident,” meaning they are very confident in all 4 categories above.";



$('#dropdown-result-1').html(DropdownResult1);
$('#dropdown-result-2').html(DropdownResult2);
$('#subhero-1').html(subHero1);
$('#subhero-d-1').html(subHeroD1);
$('#subhero-2').html(subHero2);
$('#subhero-d-2').html(subHeroD2);
$('#subhero-3').html(subHero3);
$('#subhero-d-3').html(subHeroD3);
$('#subhero-4').html(subHero4);
$('#subhero-d-4').html(subHeroD4);
$('#subhero-5').html(subHero5);
$('#subhero-d-5').html(subHeroD5);
$('#ht-card-1').css('display', htCard1);     
$('#ht-stat-1').html(htStat1);
$('#ht-subhead-1').html(htSubHead1);
$('#ht-card-2').css('display', htCard2);
$('#ht-stat-2').html(htStat2);
$('#ht-subhead-2').html(htSubHead2);
$('#ht-card-3').css('display', htCard3);
$('#ht-stat-3').html(htStat3);
$('#ht-subhead-3').html(htSubHead3);
$('#ht-card-4').css('display', htCard4);
$('#ht-stat-4').html(htStat4);
$('#ht-subhead-4').html(htSubHead4);
$('#ht-stat-5').html(htStat5);
$('#ht-subhead-5').html(htSubHead5);
$('#ht-card-6').css('display', htCard6);
$('#exp-title').html(ExpTitle);
$('#exp-1').html(Exp1);
$('#exp-2').html(Exp2);
$('#exp-3').html(Exp3);
$('#exp-4').html(Exp4);
$('#exp-wrap').css('display',ExpWrap);
$('#graph-1-wrap').css('display',Graph1);
$('#1st-yellow').css('width', yellow1);
$('#1st-green').css('width', green1);
$('#2nd-yellow').css('width', yellow2);
$('#2nd-green').css('width', green2);
$('#3rd-yellow').css('width', yellow3);
$('#3rd-green').css('width', green3);
$('#4th-yellow').css('width', yellow4);
$('#4th-green').css('width', green4);
$('#5th-yellow').css('width', yellow5);
$('#5th-green').css('width', green5);
$('#6th-yellow').css('width', yellow6);
$('#6th-green').css('width', green6);
$('#7th-yellow').css('width', yellow7);
$('#7th-green').css('width', green7);
$('#8th-yellow').css('width', yellow8);
$('#8th-green').css('width', green8);
$('#9th-yellow').css('width', yellow9);
$('#9th-green').css('width', green9);
$('#10th-yellow').css('width', yellow10);
$('#10th-green').css('width', green10);
$('#11th-yellow').css('width', yellow11);
$('#11th-green').css('width', green11);
$('#12th-yellow').css('width', yellow12);
$('#12th-green').css('width', green12);
$('#13th-yellow').css('width', yellow13);
$('#13th-green').css('width', green13);
$('#14th-yellow').css('width', yellow14);
$('#14th-green').css('width', green14);
$('#15th-yellow').css('width', yellow15);
$('#15th-green').css('width', green15);
$('#rw-section').css('display', rwSection);
$('#rw-subhead').html(RwSubhead);
$('#round-1').data('percent', round1);
$('#ap-1').html(round1);
$('#round-2').data('percent', round2);
$('#ap-2').html(round2);
$('#round-3').data('percent', round3);
$('#ap-3').html(round3);
$('#round-4').data('percent', round4);
$('#ap-4').html(round4);
$('#round-5').data('percent', round5);
$('#ap-5').html(round5);
$('#round-6').data('percent', round6);
$('#ap-6').html(round6);
$('#round-7').data('percent', round7);
$('#ap-7').html(round7);
$('#round-8').data('percent', round8);
$('#ap-8').html(round8);
$('#round-9').data('percent', round9);
$('#ap-9').html(round9);
$('#relying-main').html(relyingMain);
$('#relying-stat-1').html(relyingStat1);
$('#relying-stat-2').html(relyingStat2);
$('#relying-main-2').html(relyingMain2);
$('#relying-stat-3').html(relyingStat3);
$('#relying-stat-4').html(relyingStat4);
$('#graph-2').css('display', graph2);
$('#graph-2-title').html(graph2Title);
$('#first-top').css('height', firstTop);
$('#first-top-stat').html(firstTop);
$('#first-bot').css('height', firstBot);
$('#first-bot-stat').html(firstBot);
$('#second-top').css('height', secondTop);
$('#second-top-stat').html(secondTop);
$('#second-bot').css('height', secondBot);
$('#second-bot-stat').html(secondBot);
$('#single').css('display',singleWrap);
$('#single-title').html(singleTitle);
$('#single-stat').html(singleStat);
$('#single-desc').html(singleDesc);
$('#double').css('display', doubleWrap);
$('#double-title').html(doubleTitle);
$('#double-stat-1').html(doubleStat1);
$('#double-desc-1').html(doubleDesc1);
$('#double-stat-2').html(doubleStat2);
$('#double-desc-2').html(doubleDesc2);
$('#graph-3').css('display', graph3);
$('#dif-line-1').css('width', difStat1);
$('#dif-line-2').css('width', difStat2);
$('#dif-line-3').css('width', difStat3);
$('#dif-line-4').css('width', difStat4);
$('#dif-line-5').css('width', difStat5);
$('#dif-line-6').css('width', difStat6);
$('#dif-line-7').css('width', difStat7);
$('#dif-line-8').css('width', difStat8);
$('#dif-line-9').css('width', difStat9);
$('#dif-line-10').css('width', difStat10);
$('#dif-line-11').css('width', difStat11);
$('#dif-line-12').css('width', difStat12);
$('#dif-line-13').css('width', difStat13);
$('#dif-line-14').css('width', difStat14);
$('#dif-line-15').css('width', difStat15);
$('#turnover-1').html(turnover1);
$('#turnover-desc').html(turnoverDesc);
$('#graph-4').css('display',graph4);
$('#graph-4-title').html(graph4Title);
$('#graph-4-desc').html(graph4Desc);
$('#1st-lila').css('width', lila1);
$('#2nd-lila').css('width', lila2);
$('#3rd-lila').css('width', lila3);
$('#4th-lila').css('width', lila4);
$('#5th-lila').css('width', lila5);
$('#productivity').html(productivity);
$('#round-10').data('percent', round10);
$('#ap-10').html(round10);
$('#round-11').data('percent', round11);
$('#ap-11').html(round11);
$('#round-12').data('percent', round12);
$('#ap-12').html(round12);
$('#round-13').data('percent', round13);
$('#ap-13').html(round13);
$('#round-14').data('percent', round14);
$('#ap-14').html(round14);
$('#round-15').data('percent', round15);
$('#ap-15').html(round15);
$('#round-16').data('percent', round16);
$('#ap-16').html(round16);
$('#round-17').data('percent', round17);
$('#ap-17').html(round17);
$('#round-18').data('percent', round18);
$('#ap-18').html(round18);
$('#round-19').data('percent', round19);
$('#ap-19').html(round19);
$('#round-20').data('percent', round20);
$('#ap-20').html(round20);
$('#round-21').data('percent', round21);
$('#ap-21').html(round21);
$('#round-22').data('percent', round22);
$('#ap-22').html(round22);
$('#round-23').data('percent', round23);
$('#ap-23').html(round23);
$('#round-24').data('percent', round24);
$('#ap-24').html(round24);
$('#con-title-1').html(conTitle1);
$('#con-stat-1').html(conStat1);
$('#con-desc-1').html(conDesc1);
$('#con-desc-1-2').html(conDesc12);
$('#con-title-2').html(conTitle2);
$('#con-stat-2').html(conStat2);
$('#con-desc-2').html(conDesc2);
$('#con-title-3').html(conTitle3);
$('#con-stat-3').html(conStat3);
$('#con-desc-3').html(conDesc3);
$('#con-title-4').html(conTitle4);
$('#con-stat-4').html(conStat4);
$('#con-desc-4').html(conDesc4);
$('#con-title-5').html(conTitle5);
$('#con-stat-5').html(conStat5);
$('#con-desc-5').html(conDesc5);
});
});
